function Hd = filter_bandpass
%FILTER_BANDPASS Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.12 and the Signal Processing Toolbox 6.15.
%
% Generated on: 25-Jun-2013 17:49:04
%

% Butterworth Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in Hz.
Fs = 167;  % Sampling Frequency

Fstop1 = 7;           % First Stopband Frequency
Fpass1 = 10;          % First Passband Frequency
Fpass2 = 35;          % Second Passband Frequency
Fstop2 = 40;          % Second Stopband Frequency
Astop1 = 72;          % First Stopband Attenuation (dB)
Apass  = 1;           % Passband Ripple (dB)
Astop2 = 72;          % Second Stopband Attenuation (dB)
match  = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'butter', 'MatchExactly', match);

% [EOF]
