function [Inline1,Xline,Xcoord,YCoord,Z,XOffset,YOffset,Selectionstatus,ig,scan_digi_gradient_w_rang,scan_digi_intercept_w_ran,scan_digi_minimum_energy_] = importfile(filename, startRow, endRow)
%% ------------------ Disclaimer  ------------------
% 
% BG Group plc or any of its respective subsidiaries, affiliates and 
% associated companies (or by any of their respective officers, employees 
% or agents) makes no representation or warranty, express or implied, in 
% respect to the quality, accuracy or usefulness of this repository. The code
% is this repository is supplied with the explicit understanding and 
% agreement of recipient that any action taken or expenditure made by 
% recipient based on its examination, evaluation, interpretation or use is 
% at its own risk and responsibility.
% 
% No representation or warranty, express or implied, is or will be made in 
% relation to the accuracy or completeness of the information in this 
% repository and no responsibility or liability is or will be accepted by 
% BG Group plc or any of its respective subsidiaries, affiliates and 
% associated companies (or by any of their respective officers, employees 
% or agents) in relation to it.
%% ------------------ License  ------------------ 
% GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
%% github
% https://github.com/AnalysePrestackSeismic/
%% ------------------ FUNCTION DEFINITION ---------------------------------
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [INLINE1,XLINE,XCOORD,YCOORD,Z,XOFFSET,YOFFSET,SELECTIONSTATUS,IG,SCAN_DIGI_GRADIENT_W_RANG,SCAN_DIGI_INTERCEPT_W_RAN,SCAN_DIGI_MINIMUM_ENERGY_]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [INLINE1,XLINE,XCOORD,YCOORD,Z,XOFFSET,YOFFSET,SELECTIONSTATUS,IG,SCAN_DIGI_GRADIENT_W_RANG,SCAN_DIGI_INTERCEPT_W_RAN,SCAN_DIGI_MINIMUM_ENERGY_]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Inline1,Xline,Xcoord,YCoord,Z,XOffset,YOffset,Selectionstatus,ig,scan_digi_gradient_w_rang,scan_digi_intercept_w_ran,scan_digi_minimum_energy_]
%   = importfile('1kc_crossplot.xyz',2, 1530151);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/09/07 10:03:52

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Inline1 = dataArray{:, 1};
Xline = dataArray{:, 2};
Xcoord = dataArray{:, 3};
YCoord = dataArray{:, 4};
Z = dataArray{:, 5};
XOffset = dataArray{:, 6};
YOffset = dataArray{:, 7};
Selectionstatus = dataArray{:, 8};
ig = dataArray{:, 9};
scan_digi_gradient_w_rang = dataArray{:, 10};
scan_digi_intercept_w_ran = dataArray{:, 11};
scan_digi_minimum_energy_ = dataArray{:, 12};

