function createfigure(VertexNormals1, YData1, XData1, Vertices1, Faces1, FaceVertexCData1, CData1)
%CREATEFIGURE(VERTEXNORMALS1,YDATA1,XDATA1,VERTICES1,FACES1,FACEVERTEXCDATA1,CDATA1)
%  VERTEXNORMALS1:  patch vertexnormals
%  YDATA1:  patch ydata
%  XDATA1:  patch xdata
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  FACEVERTEXCDATA1:  patch facevertexcdata
%  CDATA1:  patch cdata

%  Auto-generated by MATLAB on 23-Jul-2012 17:15:29

% Create figure
figure1 = figure('XVisual',...
    '0x26 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)',...
    'PaperSize',[20.98404194812 29.67743169791],...
    'Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'CLim',[1 2]);
box(axes1,'on');

% Create patch
patch('Parent',axes1,'VertexNormals',VertexNormals1,'YData',YData1,...
    'XData',XData1,...
    'Vertices',Vertices1,...
    'Faces',Faces1,...
    'FaceColor','flat',...
    'FaceVertexCData',FaceVertexCData1,...
    'DisplayName','anomaly_volume',...
    'CData',CData1);

% Create xlabel
xlabel({'Degree of anomalousness (bin size = 0.01)'},'FontSize',20);

% Create ylabel
ylabel({'Counts per bin'},'FontSize',20);

% Create title
title({'Degree of anomalous for example data distribution defined using model cumulative distribution function'},...
    'FontSize',20);

